### ISSUE TITLE
Client meeting: 2/9

### ISSUE THREAD

**Issue by alyoshenka** [brandondombrowsky/BastCastle#103]
### Required
- [x] CI System demo
- [x] One user story per person
- [x] List of what is needed to finish: #104 

#### Other
- [x] Mention that locks are on hold right now because we have higher priorities

[Scrum Quicksheet](https://docs.google.com/document/d/1uh_FBVtvETK8yrUCp60gDyA3nT8OkSuKemorynn11Rg/edit#), if anyone needs to easily reference

**Comment by alyoshenka** [comment]
"You definitely need *some* linting"

**Comment by brandondombrowsky** [comment]
Complete
