### ISSUE TITLE
Edit product scripts to meet client requirements--the if/else of it

### ISSUE THREAD

**Issue by brandondombrowsky** [brandondombrowsky/BastCastle#119]
As the client, I have some specialized needs. Instead of using voice commands to say "lock" or "unlock", I may instead wish for the program to respond with "perimeters secured" when I say "lock" at the end of the day.

- [ ] I will know this issue is complete when I can test it locally and it responds as directed.

**Comment by alyoshenka** [comment]
Maybe make this issue more specific? It seems a bit too broad as-is.
