### ISSUE TITLE
Damper Script

### ISSUE THREAD

**Issue by itsjpb** [brandondombrowsky/BastCastle#120]
As a user, I want to be able to control different HVAC zones in my residence because I want to heat/cool more efficiently and hopefully save on the associated energy costs.

Tasks:
- [x] Write test script within home assistant.
- [x] Migrate test script to prod environment.
- [ ] Test script in prod environment.

Acceptance Criteria:
- [ ] Script is deployed on the primary HA instance.
- [ ] Functionality meets stakeholder/client criteria of controlling different zones.
- [ ] Script does not allow both dampers to be closed.

**Comment by LucasKnezevich** [comment]
A test script has been written, and covered the general functionality/requirements set forth by the stakeholder.

Blocking:  A prod HA instance to migrate this to.
