### ISSUE TITLE
Update yamllint rules per HA syntax

### ISSUE THREAD

**Issue by LucasKnezevich** [brandondombrowsky/BastCastle#152]
As a developer, I want our yamllint tests for HA yaml files to accept the yaml syntax generated by HA because this will prevent the files from having to be edited each time HA generated yaml is pushed into our repo.

Tasks:
- [x] Figure out the best way to go about this.  [See this.](https://github.com/frenck/action-yamllint#using-a-custom-yamllint-configuration-file)
- [x] Update the yamllint rules to accept the syntax generated by HA.
- [x] Run some tests to see if the expected outcomes are being returned by yamllint.

Acceptance Criteria:
- [x] HA-generated YAML files that pass HA-specific tests also pass the yamllint lint tests without having to be edit syntax.

**Comment by alyoshenka** [comment]
Take a look at [this](https://github.com/marketplace/actions/frenck-s-yamllint#arguments) reference for how to use your own yamllint config file.
