### ISSUE TITLE
Move documentation forward.

### ISSUE THREAD

**Issue by brandondombrowsky** [brandondombrowsky/BastCastle#172]
As a future project manager, I will take on the role of moving the documentation forward. This will include following up on the contents/assignee of the ReadMe and Wiki.

ReadMe revisions (Related #91)
Wiki - Home (Related #173)
Wiki - Application Architecture (Related #174)
Wiki - Editing user permissions in Home Assistant (Related #175)
Wiki - Notes Alexi (Related #177)
Wiki - Wiregaurd VPN Setup (Related #178)

**Comment by LucasKnezevich** [comment]
Added myself to this issue as I didn't think it was totally necessary for the few changes I made in PR #172, so I figured I'd reference this issue since it helps move the documentation forward in a very small way.
