### ISSUE TITLE
Move Wiki - Editing user permissions in Home Assistant forward.

### ISSUE THREAD

**Issue by brandondombrowsky** [brandondombrowsky/BastCastle#175]
As a developer, it is important to ensure my documentation is useful.

- [ ] Fully flush out the ideas and create a pre-final rough draft

**Comment by alyoshenka** [comment]
LGTM, but take a [look](https://github.com/brandondombrowsky/BastCastle/wiki/Editing-User-Permissions-in-Home-Assistant) and reopen if necessary.
