### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by alyoshenka** [brandondombrowsky/BastCastle#21]
expand later, placeholder for now

could maybe put some super simple CI in just to get a base + for practice?

**Comment by brandondombrowsky** [comment]
I'm gonna leave this alone until you folks tell me what kind of restrictions you want. Whatever I add will make your PRs more challenging to push as they will be run against the chosen CI stipulations (for example, a linter). That is both an interest and a deterrent for me. Yes, it would be great practice for me to implement CIs for practice, but I think if we are going to add more restrictions, we would need to agree to work together to problem-solve any failures as a team. This is a collaborative endeavor, and I believe we will be most successful in solving CI errors collaboratively. Some of us are newer after all and CI errors are no joke. What do you think?
