### ISSUE TITLE
research GA/HA/Devices

### ISSUE THREAD

**Issue by itsjpb** [brandondombrowsky/BastCastle#28]
As a developer, I want an understanding of how best to transmit data from Google Assistant to Home Assistant to IoT devices and back. May require additional research per device type. 

Considerations:

- VPN?
- VPC?
- Home Assistant Cloud & costs: #79 

Depends on #58, #44, #78

**Comment by alyoshenka** [comment]
- [ ] Home Assistant Cloud considerations:
- [ ] Public IP for EC2 instance running Home Assistant considerations:
- [ ] VPN to connect local devices to cloud instance considerations:
- [ ] VPC considerations:
