### ISSUE TITLE
Home Assistant Scripting

### ISSUE THREAD

**Issue by itsjpb** [brandondombrowsky/BastCastle#30]
As a developer, I want to understand Home Assistant scripting conventions so I can easily write automation scripts for our components.

- [x] Research Home Assistant Automation: [here](https://www.home-assistant.io/docs/automation/basics/)
  - Turns out you can do automation in the UI: [link](https://www.home-assistant.io/docs/automation/editor/)
- [x] Make an automation with the UI
- ~~[ ] Make an automation with a script~~
  - Home Assistant [Scripting Reference](https://www.home-assistant.io/docs/scripts/)
  - turns out there's a visual editor for scripts as well
- [x] devices can be controlled by scripts
  - [x] Test condition: turn one light red, sleep, if that light is red turn the other light red, sleep, turn one light blue; repeat
- [x] Discuss with team on how to appropriately add script to the repo 
  - will be decided with resolution of below PR
- [x] Add the script to HA UI and be able to turn it on/off with a toggle
  - just add the Entity through the UI
- [x] How to access light color?
  - It seems light color is from Effects, and lights are controlled with Scenes

[Associated PR](https://github.com/brandondombrowsky/BastCastle/pull/57)

**Comment by alyoshenka** [comment]
Light flip/flop automation


![Image](https://user-images.githubusercontent.com/38815390/213939791-5d3a6dd2-27a4-450f-bd65-1fca0a1779b8.png)

https://user-images.githubusercontent.com/38815390/213939828-0697f543-f8bb-4c51-8b28-f2f654a6b4dd.mp4

**Comment by alyoshenka** [comment]
Left off [here](https://www.home-assistant.io/docs/scripts/#raise-and-consume-custom-events)

**Comment by alyoshenka** [comment]
https://user-images.githubusercontent.com/38815390/214152277-5c78c232-b6bc-417c-b505-82f1d81e63cf.mp4

![Image](https://user-images.githubusercontent.com/38815390/214152324-32befe3d-79c6-4b75-88ef-4de888d81fc1.png)

![Image](https://user-images.githubusercontent.com/38815390/214152346-31d5f360-088b-4e33-b924-b6898d0548a4.png)

**Comment by alyoshenka** [comment]
![Image](https://user-images.githubusercontent.com/38815390/214153109-464b1324-40ac-48dd-8058-e7623d918b33.png)
