### ISSUE TITLE
Add diagram to ReadMe (if necessary)

### ISSUE THREAD

**Issue by brandondombrowsky** [brandondombrowsky/BastCastle#52]
If your diagram should live in  the ReamMe, add it! 

- [x] I will know this is complete when the agreed upon diagrams are within ReadMe
- [x] Alexi: not necessary

**Comment by alyoshenka** [comment]
I think they're fine in the wiki, because the ReadMe is typically used as a general introduction to the project (and sometimes installation instructions). Maybe link the wiki there though? something like "For more information go here [link]"
