### ISSUE TITLE
Door lock HA integration

### ISSUE THREAD

**Issue by VictorHugoNava** [brandondombrowsky/BastCastle#64]
As a developer, I will want the door locks integrated with HA. 

- [ ] I will know this issue is complete when I have locks to test, and
- [ ] Lock(s) connected to HA

**Comment by alyoshenka** [comment]
Blocked until VPN is set up.

**Comment by alyoshenka** [comment]
Locks don't connect to HA (unfortunately). Closing in favor of #65
