### ISSUE TITLE
Assist with someone else trying S-t-S VPN

### ISSUE THREAD

**Issue by alyoshenka** [brandondombrowsky/BastCastle#86]
Same user story as #78, see notes in that issue as to why I couldn't get it set up.
Related #78

**Comment by itsjpb** [comment]
##openVPN on Pi

- [server setup](https://youtu.be/Iwoznebw88o)
- [client setup](https://youtu.be/ym6O482tDQk)

Does not work without further configuration

- [site-to-site setup](https://openvpn.net/solutions/use-cases/site-to-site-vpn/)
- requires unsupported router
