### ISSUE TITLE
Finalize smart damper design.

### ISSUE THREAD

**Issue by LucasKnezevich** [brandondombrowsky/BastCastle#96]
As I user, I want to know exactly what is needed to implement a smart damper solution in my home because I need to know what to purchase and how to install it.

Tasks:
- [x] Develop comprehensive list of questions for client and send them for review.
- [x] Review answers from client and ensure the damper design aligns with their responses.  Adjust design accordingly.
- [x] Repeat above two steps until full design is complete and is functional per the client's system requirements.
- [x] Send material list to client for purchase.

**Comment by itsjpb** [comment]
awaiting more information on Kyle's HVAC; all other details prepared

**Comment by LucasKnezevich** [comment]
The design is essentially done.  We've encountered issues getting the desired dampers, but the concept/design and general materials were reviewed/approved.
