### ISSUE TITLE
Research & implement YAML linting.

### ISSUE THREAD

**Issue by LucasKnezevich** [brandondombrowsky/BastCastle#98]
As a developer, I want all YAML files being pushed up to GH to undergo linting because it will help ensure my code is formatted correctly.

*Note: This issue is just for the initial implementation, additional issues will be created as we identify how it should evolve.*

Tasks:
- [x] Explore linting options for YAML files.
- [x] Propose solution to team.
- [x] Implement solution.

Complete When:
- [x] YAML files being pushed into BastCastle are being linted as expected.

**Comment by LucasKnezevich** [comment]
[Solution here might be promising.](https://stackoverflow.com/questions/71334373/is-there-a-way-i-can-validate-yaml-files-on-github)

**Comment by LucasKnezevich** [comment]
### Feedback from Kyle to Brandon's post:

Your CI component should at least look like this:
- Build (in this case validate you have correct yaml files)
- Lint (in this case validate that you have correctly formatted yaml files)
- Test (in this case I would try and validate if your yaml files follow a known Home Assistant schema, but this might be covered by your build step)

- You could achieve your build through somethign like this: https://www.npmjs.com/package/yaml-validator
- You could achieving linting through something like this: https://github.com/ota-meshi/eslint-plugin-yml
- You could achieve testing through something like this, but it also looks like the build tool I mentioned above has a bit of this: https://www.npmjs.com/package/yaml-schema-validator

**Comment by LucasKnezevich** [comment]
### Brandon found:

I also found a more helpful (maybe) article. It says it is "easy" to set up lol: https://github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps/

**Comment by LucasKnezevich** [comment]
### Logging anymore resources I find in this comment.
[eslint-plugin-yml rules](https://ota-meshi.github.io/eslint-plugin-yml/rules/)

**Comment by brandondombrowsky** [comment]
Completed Thursday night. Our files are not passing, as expected, as the formatting is off. As of now, HA files are passing the linter, the yaml files, however, are failing.
